//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ZippingWorker_Service.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZippingWorker_ServiceConfigurationSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("zippingworker_serviceconfiguration", Namespace="http://tempuri.org/ZippingWorker_ServiceConfigurationSchema.xsd", IsNullable=false)]
    public partial class ZippingWorker_ServiceConfigurationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MetaDataType[] metadataloggingField;
        
        private int serviceportField;
        
        private string sevenzipexepathField;
        
        private string tempdir_symlinkField;
        
        private bool tempdir_symlink_createIfNotExistField;
        
        private string tempdir_zipstagingField;
        
        private bool tempdir_zipstaging_createIfNotExistField;
        
        private ArchiverEnumType archiverField;
        
        private CompressionLevelEnumType compressionlevelField;
        
        public ZippingWorker_ServiceConfigurationType() {
            this.serviceportField = 5000;
            this.sevenzipexepathField = "7z.exe";
            this.tempdir_symlinkField = "%APPPATH%\\tempsymlink";
            this.tempdir_symlink_createIfNotExistField = true;
            this.tempdir_zipstagingField = "%APPPATH%\\tempzip";
            this.tempdir_zipstaging_createIfNotExistField = true;
            this.archiverField = ArchiverEnumType.sevenzip;
            this.compressionlevelField = CompressionLevelEnumType.ultra;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MetaDataType[] metadatalogging {
            get {
                return this.metadataloggingField;
            }
            set {
                this.metadataloggingField = value;
                this.RaisePropertyChanged("metadatalogging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(5000)]
        public int serviceport {
            get {
                return this.serviceportField;
            }
            set {
                this.serviceportField = value;
                this.RaisePropertyChanged("serviceport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("7z.exe")]
        public string sevenzipexepath {
            get {
                return this.sevenzipexepathField;
            }
            set {
                this.sevenzipexepathField = value;
                this.RaisePropertyChanged("sevenzipexepath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("%APPPATH%\\tempsymlink")]
        public string tempdir_symlink {
            get {
                return this.tempdir_symlinkField;
            }
            set {
                this.tempdir_symlinkField = value;
                this.RaisePropertyChanged("tempdir_symlink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool tempdir_symlink_createIfNotExist {
            get {
                return this.tempdir_symlink_createIfNotExistField;
            }
            set {
                this.tempdir_symlink_createIfNotExistField = value;
                this.RaisePropertyChanged("tempdir_symlink_createIfNotExist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("%APPPATH%\\tempzip")]
        public string tempdir_zipstaging {
            get {
                return this.tempdir_zipstagingField;
            }
            set {
                this.tempdir_zipstagingField = value;
                this.RaisePropertyChanged("tempdir_zipstaging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool tempdir_zipstaging_createIfNotExist {
            get {
                return this.tempdir_zipstaging_createIfNotExistField;
            }
            set {
                this.tempdir_zipstaging_createIfNotExistField = value;
                this.RaisePropertyChanged("tempdir_zipstaging_createIfNotExist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ArchiverEnumType.sevenzip)]
        public ArchiverEnumType archiver {
            get {
                return this.archiverField;
            }
            set {
                this.archiverField = value;
                this.RaisePropertyChanged("archiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CompressionLevelEnumType.ultra)]
        public CompressionLevelEnumType compressionlevel {
            get {
                return this.compressionlevelField;
            }
            set {
                this.compressionlevelField = value;
                this.RaisePropertyChanged("compressionlevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZippingWorker_ServiceConfigurationSchema.xsd")]
    public partial class MetaDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZippingWorker_ServiceConfigurationSchema.xsd")]
    public enum ArchiverEnumType {
        
        /// <remarks/>
        sevenzip,
        
        /// <remarks/>
        dotnetzip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZippingWorker_ServiceConfigurationSchema.xsd")]
    public enum CompressionLevelEnumType {
        
        /// <remarks/>
        nocompression,
        
        /// <remarks/>
        fastest,
        
        /// <remarks/>
        fast,
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        maximum,
        
        /// <remarks/>
        ultra,
    }
}
