//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ZippingWorker_Service.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZipInfoSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("zippingfiles", Namespace="http://tempuri.org/ZipInfoSchema.xsd", IsNullable=false)]
    public partial class ZipInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zipfilenameField;
        
        private string zipfiledirectoryField;
        
        private CompressionLevelEnumType zipcompressionlevelField;
        
        private ValidateEnumType validatezippingField;
        
        private DeleteEnumType deleteinputfilesField;
        
        private DriveLetterType[] drivelettersField;
        
        private FileInfoType[] zipfilesField;
        
        private MetaDataType[] metadataField;
        
        public ZipInfoType() {
            this.zipfiledirectoryField = "";
            this.zipcompressionlevelField = CompressionLevelEnumType.ultra;
            this.validatezippingField = ValidateEnumType.extract;
            this.deleteinputfilesField = DeleteEnumType.recyclebin;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zipfilename {
            get {
                return this.zipfilenameField;
            }
            set {
                this.zipfilenameField = value;
                this.RaisePropertyChanged("zipfilename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string zipfiledirectory {
            get {
                return this.zipfiledirectoryField;
            }
            set {
                this.zipfiledirectoryField = value;
                this.RaisePropertyChanged("zipfiledirectory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(CompressionLevelEnumType.ultra)]
        public CompressionLevelEnumType zipcompressionlevel {
            get {
                return this.zipcompressionlevelField;
            }
            set {
                this.zipcompressionlevelField = value;
                this.RaisePropertyChanged("zipcompressionlevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(ValidateEnumType.extract)]
        public ValidateEnumType validatezipping {
            get {
                return this.validatezippingField;
            }
            set {
                this.validatezippingField = value;
                this.RaisePropertyChanged("validatezipping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(DeleteEnumType.recyclebin)]
        public DeleteEnumType deleteinputfiles {
            get {
                return this.deleteinputfilesField;
            }
            set {
                this.deleteinputfilesField = value;
                this.RaisePropertyChanged("deleteinputfiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("driveletter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DriveLetterType[] driveletters {
            get {
                return this.drivelettersField;
            }
            set {
                this.drivelettersField = value;
                this.RaisePropertyChanged("driveletters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fileinfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FileInfoType[] zipfiles {
            get {
                return this.zipfilesField;
            }
            set {
                this.zipfilesField = value;
                this.RaisePropertyChanged("zipfiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MetaDataType[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZipInfoSchema.xsd")]
    public enum CompressionLevelEnumType {
        
        /// <remarks/>
        nocompression,
        
        /// <remarks/>
        fastest,
        
        /// <remarks/>
        fast,
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        maximum,
        
        /// <remarks/>
        ultra,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZipInfoSchema.xsd")]
    public enum ValidateEnumType {
        
        /// <remarks/>
        extract,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7zip")]
        Item7zip,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZipInfoSchema.xsd")]
    public enum DeleteEnumType {
        
        /// <remarks/>
        delete,
        
        /// <remarks/>
        recyclebin,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZipInfoSchema.xsd")]
    public partial class DriveLetterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MetaDataType[] metadataField;
        
        private string driveletterField;
        
        private string drivepathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MetaDataType[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string driveletter {
            get {
                return this.driveletterField;
            }
            set {
                this.driveletterField = value;
                this.RaisePropertyChanged("driveletter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drivepath {
            get {
                return this.drivepathField;
            }
            set {
                this.drivepathField = value;
                this.RaisePropertyChanged("drivepath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZipInfoSchema.xsd")]
    public partial class MetaDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ZipInfoSchema.xsd")]
    public partial class FileInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MetaDataType[] metadataField;
        
        private string filelocationField;
        
        private string filehashField;
        
        private string internalziplocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MetaDataType[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filelocation {
            get {
                return this.filelocationField;
            }
            set {
                this.filelocationField = value;
                this.RaisePropertyChanged("filelocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filehash {
            get {
                return this.filehashField;
            }
            set {
                this.filehashField = value;
                this.RaisePropertyChanged("filehash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string internalziplocation {
            get {
                return this.internalziplocationField;
            }
            set {
                this.internalziplocationField = value;
                this.RaisePropertyChanged("internalziplocation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
